DOCTOR_ROLE = "DOCTOR_ROLE"
CAN_SEE_EXTRA_FIELDS = "CAN_SEE_EXTRA_FIELDS"

# no longer relevant, everyone can see all peak flows
CAN_SEE_PEAK_FLOW = "CAN_SEE_PEAK_FLOW"
CAN_SEE_TRIALS_FROM_PEAK_FLOW_DB = "CAN_SEE_TRIALS_FROM_PEAK_FLOW_DB"
