# Generated by Django 2.0.9 on 2019-01-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_auto_20190123_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'verbose_name': 'General notes'},
        ),
    ]
