# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_bloodbook_bloodbookresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='oh_provider',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
