# Generated by Django 2.0.13 on 2019-12-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('legacy', '0003_auto_20190130_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_id', models.IntegerField()),
                ('occmedno', models.IntegerField()),
                ('trial_num', models.IntegerField()),
                ('trial_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('trial_deleted', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='OccTrialDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occmedno', models.IntegerField()),
                ('trial_num', models.IntegerField()),
                ('drug_code', models.IntegerField()),
                ('work_start', models.IntegerField()),
                ('work_finish', models.IntegerField()),
                ('published', models.BooleanField()),
                ('flow_0000', models.IntegerField(verbose_name='00:00')),
                ('flow_0100', models.IntegerField(verbose_name='01:00')),
                ('flow_0200', models.IntegerField(verbose_name='02:00')),
                ('flow_0300', models.IntegerField(verbose_name='03:00')),
                ('flow_0400', models.IntegerField(verbose_name='04:00')),
                ('flow_0500', models.IntegerField(verbose_name='05:00')),
                ('flow_0600', models.IntegerField(verbose_name='06:00')),
                ('flow_0700', models.IntegerField(verbose_name='07:00')),
                ('flow_0800', models.IntegerField(verbose_name='08:00')),
                ('flow_0900', models.IntegerField(verbose_name='09:00')),
                ('flow_1000', models.IntegerField(verbose_name='10:00')),
                ('flow_1100', models.IntegerField(verbose_name='11:00')),
                ('flow_1200', models.IntegerField(verbose_name='12:00')),
                ('flow_1300', models.IntegerField(verbose_name='13:00')),
                ('flow_1400', models.IntegerField(verbose_name='14:00')),
                ('flow_1500', models.IntegerField(verbose_name='15:00')),
                ('flow_1600', models.IntegerField(verbose_name='16:00')),
                ('flow_1700', models.IntegerField(verbose_name='17:00')),
                ('flow_1800', models.IntegerField(verbose_name='18:00')),
                ('flow_1900', models.IntegerField(verbose_name='19:00')),
                ('flow_2000', models.IntegerField(verbose_name='20:00')),
                ('flow_2100', models.IntegerField(verbose_name='21:00')),
                ('flow_2200', models.IntegerField(verbose_name='22:00')),
                ('flow_2300', models.IntegerField(verbose_name='23:00')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
        migrations.RenameField(
            model_name='peakflowidentifier',
            old_name='occmendo',
            new_name='occmedno',
        ),
    ]
