# Generated by Django 2.0.13 on 2020-03-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_auto_20190130_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakflowidentifier',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
