# Generated by Django 2.0.9 on 2019-02-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_auto_20190130_1619'),
        ('legacy', '0003_auto_20190130_1339'),
    ]

    operations = [
    ]
