# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_auto_20181107_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionlog',
            name='clinicdate',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='date_of_followup',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='diagnosis_made',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='follow_up_planned',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='letters',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='seen_by',
        ),
    ]
