# Generated by Django 2.0.13 on 2020-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_address_bronchialtest_details_diagnosticasthma_diagnosticother_diagnosticoutcome_diagnosticrhinitis_'),
        ('legacy', '0004_peakflowidentifier_age'),
    ]

    operations = [
    ]
