# Generated by Django 2.0.13 on 2019-12-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_auto_20191205_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='occtrialday',
            name='day_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
