# Generated by Django 2.0.13 on 2020-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_merge_20200430_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinespt',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
