# Generated by Django 2.0.13 on 2019-12-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_occtrialday_day_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occtrial',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
        ),
        migrations.AlterField(
            model_name='occtrialday',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
        ),
        migrations.AlterField(
            model_name='peakflowidentifier',
            name='occmedno',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
