# Generated by Django 2.0.13 on 2020-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_merge_20200427_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='referring_doctor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='specialist_doctor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
