# Generated by Django 2.0.13 on 2019-03-22 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('legacy', '0005_details_diagnosticasthma_diagnosticother_diagnosticoutcome_diagnosticrhinitis_diagnostictesting_othe'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronchialTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('bronchial_num', models.TextField(blank=True, null=True)),
                ('substance', models.TextField(blank=True, null=True)),
                ('last_exposed', models.TextField(blank=True, null=True)),
                ('duration_exposed', models.TextField(blank=True, null=True)),
                ('date_of_challenge', models.TextField(blank=True, null=True)),
                ('foo', models.TextField(blank=True, null=True)),
                ('other_type', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('baseline_pc290', models.TextField(blank=True, null=True)),
                ('lowest_pc20', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legacy_bronchialtest_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legacy_bronchialtest_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
