# Generated by Django 2.0.13 on 2019-12-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_auto_20191205_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occtrial',
            unique_together={('trial_id', 'occmedno', 'trial_num', 'trial_deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='occtrialday',
            unique_together={('trial_num', 'occmedno', 'day_num', 'published')},
        ),
    ]
