# Generated by Django 2.0.13 on 2020-04-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_routinespt_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='referring_doctor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='specialist_doctor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspectoccupationalcategory',
            name='employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='date_referral_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
