# Generated by Django 2.0.13 on 2020-04-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_auto_20200428_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='employer',
        ),
    ]
