# Generated by Django 2.0.13 on 2019-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_routinespt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinespt',
            name='alternaria',
        ),
        migrations.RemoveField(
            model_name='routinespt',
            name='clad',
        ),
        migrations.RemoveField(
            model_name='routinespt',
            name='dog',
        ),
        migrations.AlterField(
            model_name='routinespt',
            name='asp_fumigatus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinespt',
            name='cat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinespt',
            name='d_pter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinespt',
            name='grass_pollen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinespt',
            name='neg_control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routinespt',
            name='pos_control',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
