# Generated by Django 2.0.13 on 2020-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0007_auto_20200624_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnumber',
            name='source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
