# Generated by Django 2.0.13 on 2020-09-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_patientnumber_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbook',
            name='referrername',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bloodbook',
            name='referrerttl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
