# Generated by Django 2.0.13 on 2020-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_auto_20200504_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictesting',
            name='ct_chest_scan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='full_lung_function_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
