# Generated by Django 2.0.13 on 2019-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0008_auto_20190322_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronchialtest',
            name='bronchial_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bronchialtest',
            name='date_of_challenge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bronchialtest',
            name='last_exposed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
