# Generated by Django 2.0.13 on 2020-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0009_auto_20200505_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoutcome',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
