# Generated by Django 2.0.13 on 2020-10-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0038_auto_20191206_1449'),
        ('legacy', '0009_auto_20201020_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbook',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='consistency_token',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='bloodbook',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opal.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbookresult',
            name='blood_book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='legacy.BloodBook'),
            preserve_default=False,
        ),
    ]
