# Generated by Django 2.0.13 on 2020-09-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0009_auto_20200906_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbook',
            old_name='referrername',
            new_name='referrer_name',
        ),
        migrations.RenameField(
            model_name='bloodbook',
            old_name='referrerttl',
            new_name='referrer_title',
        ),
    ]
