# Generated by Django 2.0.13 on 2020-09-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0009_auto_20200921_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbookepisode',
            name='blood_number',
        ),
    ]
