# Generated by Django 2.0.13 on 2019-03-22 14:45

from django.db import migrations


def convert_empty_to_none(apps, schema_editor):
    Details = apps.get_model("legacy", "Details")
    SuspectOccupationalCategory = apps.get_model(
        "legacy", "SuspectOccupationalCategory"
    )

    Details.objects.filter(has_asthma="").update(has_asthma=None)
    Details.objects.filter(has_eczema="").update(has_eczema=None)
    Details.objects.filter(has_hayfever="").update(has_hayfever=None)
    (SuspectOccupationalCategory.objects.filter(is_currently_employed="")
                                        .update(is_currently_employed=None))


def convert_none_to_empty(apps, schema_editor):
    Details = apps.get_model("legacy", "Details")
    SuspectOccupationalCategory = apps.get_model(
        "legacy", "SuspectOccupationalCategory"
    )

    Details.objects.filter(has_asthma=None).update(has_asthma="")
    Details.objects.filter(has_eczema=None).update(has_eczema="")
    Details.objects.filter(has_hayfever=None).update(has_hayfever="")
    (SuspectOccupationalCategory.objects.filter(is_currently_employed=None)
                                .update(is_currently_employed=""))


class Migration(migrations.Migration):

    dependencies = [("legacy", "0009_auto_20190322_1417")]

    operations = [
        migrations.RunPython(
            convert_empty_to_none,
            reverse_code=convert_none_to_empty,
        )
    ]
