# Generated by Django 2.0.13 on 2020-10-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0010_auto_20201020_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='store',
            field=models.NullBooleanField(),
        ),
    ]
