# Generated by Django 2.0.13 on 2020-09-21 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0010_remove_bloodbookepisode_blood_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbook',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='BloodBook',
        ),
        migrations.DeleteModel(
            name='BloodBookResult',
        ),
    ]
