# Generated by Django 2.0.13 on 2020-09-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0010_auto_20200906_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='blood_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbook',
            name='blood_tm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
