# Generated by Django 2.0.13 on 2019-03-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0010_auto_20190322_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_first_attended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='date_referral_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='has_asthma',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='has_eczema',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='has_hayfever',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='smokes_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suspectoccupationalcategory',
            name='is_currently_employed',
            field=models.NullBooleanField(),
        ),
    ]
