# Generated by Django 2.0.13 on 2019-03-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0011_auto_20190322_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='date_first_attended',
        ),
        migrations.RemoveField(
            model_name='details',
            name='hospital_number',
        ),
        migrations.RemoveField(
            model_name='details',
            name='referring_doctor',
        ),
    ]
