# Generated by Django 2.0.13 on 2020-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0011_auto_20201021_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='blood_tm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
