# Generated by Django 2.0.13 on 2020-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0011_auto_20200921_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbookepisode',
            name='exposures',
            field=models.TextField(blank=True, null=True),
        ),
    ]
