# Generated by Django 2.0.13 on 2020-09-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0012_bloodbookepisode_exposures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbookepisode',
            name='blood_book_patient',
        ),
        migrations.RemoveField(
            model_name='bloodbookepisode',
            name='episode',
        ),
        migrations.DeleteModel(
            name='BloodBookEpisode',
        ),
    ]
