# Generated by Django 2.0.13 on 2020-10-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0012_auto_20201021_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='antigen_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('BESPOKE', 'BESPOKE')], max_length=200, null=True),
        ),
    ]
