# Generated by Django 2.0.13 on 2019-03-25 10:04

from django.db import migrations


def empty_strings_to_none(apps, schema_editor):
    DiagnosticTesting = apps.get_model("legacy", "DiagnosticTesting")
    DiagnosticTesting.objects.filter(antihistimines="").update(
        antihistimines=None
    )
    DiagnosticTesting.objects.filter(skin_prick_test="").update(
        skin_prick_test=None
    )
    DiagnosticTesting.objects.filter(specific_skin_prick="").update(
        specific_skin_prick=None
    )
    DiagnosticTesting.objects.filter(serum_antibodies="").update(
        serum_antibodies=None
    )
    DiagnosticTesting.objects.filter(bronchial_prov_test="").update(
        bronchial_prov_test=None
    )
    DiagnosticTesting.objects.filter(nasal_prov_test="").update(
        nasal_prov_test=None
    )
    DiagnosticTesting.objects.filter(positive_reaction="").update(
        positive_reaction=None
    )
    DiagnosticTesting.objects.filter(ct_chest_scan="").update(
        ct_chest_scan=None
    )
    DiagnosticTesting.objects.filter(ct_chest_scan_date="").update(
        ct_chest_scan_date=None
    )
    DiagnosticTesting.objects.filter(full_lung_function="").update(
        full_lung_function=None
    )
    DiagnosticTesting.objects.filter(fev_1="").update(fev_1=None)
    DiagnosticTesting.objects.filter(fev_1_post_ventolin="").update(
        fev_1_post_ventolin=None
    )
    DiagnosticTesting.objects.filter(fev_1_percentage_protected="").update(
        fev_1_percentage_protected=None
    )
    DiagnosticTesting.objects.filter(fvc="").update(fvc=None)
    DiagnosticTesting.objects.filter(fvc_post_ventolin="").update(
        fvc_post_ventolin=None
    )
    DiagnosticTesting.objects.filter(fvc_percentage_protected="").update(
        fvc_percentage_protected=None
    )


def none_to_empty_string(apps, schema_editor):
    DiagnosticTesting = apps.get_model("legacy", "DiagnosticTesting")
    DiagnosticTesting.objects.filter(antihistimines=None).update(
        antihistimines=""
    )
    DiagnosticTesting.objects.filter(skin_prick_test=None).update(
        skin_prick_test=""
    )
    DiagnosticTesting.objects.filter(specific_skin_prick=None).update(
        specific_skin_prick=""
    )
    DiagnosticTesting.objects.filter(serum_antibodies=None).update(
        serum_antibodies=""
    )
    DiagnosticTesting.objects.filter(bronchial_prov_test=None).update(
        bronchial_prov_test=""
    )
    DiagnosticTesting.objects.filter(nasal_prov_test=None).update(
        nasal_prov_test=""
    )
    DiagnosticTesting.objects.filter(positive_reaction=None).update(
        positive_reaction=""
    )
    DiagnosticTesting.objects.filter(ct_chest_scan=None).update(
        ct_chest_scan=""
    )
    DiagnosticTesting.objects.filter(ct_chest_scan_date=None).update(
        ct_chest_scan_date=""
    )
    DiagnosticTesting.objects.filter(full_lung_function=None).update(
        full_lung_function=""
    )
    DiagnosticTesting.objects.filter(fev_1=None).update(fev_1="")
    DiagnosticTesting.objects.filter(fev_1_post_ventolin=None).update(
        fev_1_post_ventolin=""
    )
    DiagnosticTesting.objects.filter(fev_1_percentage_protected=None).update(
        fev_1_percentage_protected=""
    )
    DiagnosticTesting.objects.filter(fvc=None).update(fvc="")
    DiagnosticTesting.objects.filter(fvc_post_ventolin=None).update(
        fvc_post_ventolin=""
    )
    DiagnosticTesting.objects.filter(fvc_percentage_protected=None).update(
        fvc_percentage_protected=""
    )


class Migration(migrations.Migration):

    dependencies = [("legacy", "0013_auto_20190325_0829")]
    operations = [
        migrations.RunPython(
            empty_strings_to_none, reverse_code=none_to_empty_string
        )
    ]
