# Generated by Django 2.0.13 on 2020-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0013_auto_20201027_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='assayno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Assay number'),
        ),
    ]
