# Generated by Django 2.0.13 on 2020-10-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0014_auto_20201027_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='oh_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OH provider'),
        ),
        migrations.AlterField(
            model_name='bloodbookresult',
            name='antigenno',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Antigen number'),
        ),
    ]
