# Generated by Django 2.0.13 on 2019-03-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0014_auto_20190325_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictesting',
            name='antihistimines',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='bronchial_prov_test',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='ct_chest_scan',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='ct_chest_scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='fev_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='fev_1_percentage_protected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='fev_1_post_ventolin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='full_lung_function',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='fvc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='fvc_percentage_protected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='fvc_post_ventolin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='nasal_prov_test',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='positive_reaction',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='serum_antibodies',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='skin_prick_test',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='specific_skin_prick',
            field=models.NullBooleanField(),
        ),
    ]
