# Generated by Django 2.0.13 on 2020-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0015_auto_20201027_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbookresult',
            name='igg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbookresult',
            name='iggclass',
            field=models.IntegerField(blank=True, null=True, verbose_name='IgG Class'),
        ),
        migrations.AlterField(
            model_name='bloodbookresult',
            name='klass',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], null=True, verbose_name='IgE Class'),
        ),
        migrations.AlterField(
            model_name='bloodbookresult',
            name='rast',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
