# Generated by Django 2.0.13 on 2020-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0015_auto_20201027_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbookresult',
            name='rast',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
