# Generated by Django 2.0.13 on 2019-03-25 13:03

from django.db import migrations


def empty_strings_to_none(apps, schema_editor):
    DiagnosticOutcome = apps.get_model("legacy", "DiagnosticOutcome")
    DiagnosticOutcome.objects.filter(diagnosis_date="").update(diagnosis_date=None)

    DiagnosticAsthma = apps.get_model("legacy", "DiagnosticAsthma")
    DiagnosticAsthma.objects.filter(asthma="").update(asthma=None)
    DiagnosticAsthma.objects.filter(is_exacerbated_by_work="").update(
        is_exacerbated_by_work=None
    )
    DiagnosticAsthma.objects.filter(has_infant_induced_asthma="").update(
        has_infant_induced_asthma=None
    )
    DiagnosticAsthma.objects.filter(
        occupational_asthma_caused_by_sensitisation=""
    ).update(occupational_asthma_caused_by_sensitisation=None)
    DiagnosticAsthma.objects.filter(has_non_occupational_asthma="").update(
        has_non_occupational_asthma=None
    )


def none_to_empty_string(apps, schema_editor):
    DiagnosticOutcome = apps.get_model("legacy", "DiagnosticOutcome")
    DiagnosticOutcome.objects.filter(diagnosis_date=None).update(diagnosis_date="")

    DiagnosticAsthma = apps.get_model("legacy", "DiagnosticAsthma")
    DiagnosticAsthma.objects.filter(asthma=None).update(asthma="")
    DiagnosticAsthma.objects.filter(is_exacerbated_by_work=None).update(
        is_exacerbated_by_work=""
    )
    DiagnosticAsthma.objects.filter(has_infant_induced_asthma=None).update(
        has_infant_induced_asthma=""
    )
    DiagnosticAsthma.objects.filter(
        occupational_asthma_caused_by_sensitisation=None
    ).update(occupational_asthma_caused_by_sensitisation="")
    DiagnosticAsthma.objects.filter(has_non_occupational_asthma=None).update(
        has_non_occupational_asthma=""
    )


class Migration(migrations.Migration):

    dependencies = [("legacy", "0015_auto_20190325_1019")]

    operations = [
        migrations.RunPython(
            empty_strings_to_none, reverse_code=none_to_empty_string
        )
    ]
