# Generated by Django 2.0.13 on 2020-11-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0016_auto_20201118_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbookresult',
            name='klass',
            field=models.IntegerField(blank=True, null=True, verbose_name='IgE Class'),
        ),
    ]
