# Generated by Django 2.0.13 on 2019-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0016_auto_20190325_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticasthma',
            name='asthma',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticasthma',
            name='has_infant_induced_asthma',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticasthma',
            name='has_non_occupational_asthma',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticasthma',
            name='is_exacerbated_by_work',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticasthma',
            name='occupational_asthma_caused_by_sensitisation',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticoutcome',
            name='diagnosis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
