# Generated by Django 2.0.13 on 2019-03-25 13:17

from django.db import migrations


def empty_strings_to_none(apps, schema_editor):
    DiagnosticRhinitis = apps.get_model("legacy", "DiagnosticRhinitis")
    DiagnosticRhinitis.objects.filter(rhinitis="").update(rhinitis=None)
    DiagnosticRhinitis.objects.filter(work_exacerbated="").update(
        work_exacerbated=None
    )
    DiagnosticRhinitis.objects.filter(
        occupational_rhinitis_caused_by_sensitisation=""
    ).update(occupational_rhinitis_caused_by_sensitisation=None)
    DiagnosticRhinitis.objects.filter(has_non_occupational_rhinitis="").update(
        has_non_occupational_rhinitis=None
    )
    DiagnosticRhinitis.objects.filter(
        has_non_occupational_rhinitis="x",
    ).update(
        has_non_occupational_rhinitis=None
    )


def none_to_empty_string(apps, schema_editor):
    DiagnosticRhinitis = apps.get_model("legacy", "DiagnosticRhinitis")
    DiagnosticRhinitis.objects.filter(rhinitis=None).update(rhinitis="")
    DiagnosticRhinitis.objects.filter(work_exacerbated=None).update(
        work_exacerbated=""
    )
    DiagnosticRhinitis.objects.filter(
        occupational_rhinitis_caused_by_sensitisation=None
    ).update(occupational_rhinitis_caused_by_sensitisation="")
    DiagnosticRhinitis.objects.filter(
        has_non_occupational_rhinitis=None
    ).update(has_non_occupational_rhinitis="")


class Migration(migrations.Migration):

    dependencies = [("legacy", "0017_auto_20190325_1308")]

    operations = [
        migrations.RunPython(
            empty_strings_to_none, reverse_code=none_to_empty_string
        )
    ]
