# Generated by Django 2.0.13 on 2020-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0018_auto_20201130_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbook',
            name='method',
            field=models.CharField(blank=True, choices=[('ImmunoCAP', 'ImmunoCAP'), ('RAST', 'RAST'), ('RAST Score', 'RAST Score'), ('Precipitins', 'Precipitins')], max_length=200, null=True),
        ),
    ]
