# Generated by Django 2.0.13 on 2019-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0018_auto_20190325_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticrhinitis',
            name='has_non_occupational_rhinitis',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticrhinitis',
            name='occupational_rhinitis_caused_by_sensitisation',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticrhinitis',
            name='rhinitis',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticrhinitis',
            name='work_exacerbated',
            field=models.NullBooleanField(),
        ),
    ]
