# Generated by Django 2.2.16 on 2020-12-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0019_auto_20201202_1636'),
        ('legacy', '0016_auto_20201202_1135'),
    ]

    operations = [
    ]
