# Generated by Django 2.2.16 on 2020-12-10 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0020_merge_20201210_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbook',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='information',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='oh_provider',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='reference_number',
        ),
    ]
