# Generated by Django 2.0.13 on 2019-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0020_auto_20190325_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticother',
            name='NAD',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='benign_pleural_disease',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='copd',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='copd_is_occupational',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='copd_with_emphysema',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='diffuse_lung_disease',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='diffuse_lung_disease_is_occupational',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='emphysema',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='malignancy',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='malignancy_is_occupational',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='other_diagnosis',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='diagnosticother',
            name='other_diagnosis_is_occupational',
            field=models.NullBooleanField(),
        ),
    ]
