# Generated by Django 2.2.16 on 2020-12-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0021_auto_20201210_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodbookresult',
            old_name='antigenno',
            new_name='phadia_test_code',
        ),
    ]
