# Generated by Django 2.0.13 on 2019-03-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0021_auto_20190325_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherfields',
            name='bronch_prov_test_type',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='exposure_dates',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='ige_results',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='outcome_num',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='serum_results_num',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='ssp_test_num',
        ),
    ]
