# Generated by Django 2.0.13 on 2019-03-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0022_auto_20190325_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherfields',
            name='lft_date',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='perf_variability',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='perf_work_relate',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='serial_perf',
        ),
    ]
