# Generated by Django 2.2.16 on 2020-12-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0022_auto_20201211_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbook',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='exposure_fk',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='allergen_fk',
        ),
        migrations.RemoveField(
            model_name='bloodbookresult',
            name='blood_book',
        ),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
        migrations.DeleteModel(
            name='BloodBook',
        ),
        migrations.DeleteModel(
            name='BloodBookResult',
        ),
        migrations.DeleteModel(
            name='Exposure',
        ),
    ]
