# Generated by Django 2.0.13 on 2019-03-26 09:26

from django.db import migrations


def empty_strings_to_none(apps, schema_editor):
    DiagnosticTesting = apps.get_model("legacy", "DiagnosticTesting")
    DiagnosticTesting.objects.filter(full_lung_function_date="").update(
        full_lung_function_date=None
    )
    DiagnosticTesting.objects.filter(is_serial_peak_flows_requested="").update(
        is_serial_peak_flows_requested=None
    )


def none_to_empty_string(apps, schema_editor):
    DiagnosticTesting = apps.get_model("legacy", "DiagnosticTesting")
    DiagnosticTesting.objects.filter(full_lung_function_date=None).update(
        full_lung_function_date=""
    )
    DiagnosticTesting.objects.filter(is_serial_peak_flows_requested="").update(
        is_serial_peak_flows_requested=None
    )


class Migration(migrations.Migration):
    dependencies = [("legacy", "0023_auto_20190326_0904")]

    operations = [
        migrations.RunPython(
            empty_strings_to_none, reverse_code=none_to_empty_string
        )
    ]
