# Generated by Django 2.0.13 on 2019-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0024_auto_20190326_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictesting',
            name='full_lung_function_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostictesting',
            name='is_serial_peak_flows_requested',
            field=models.NullBooleanField(),
        ),
    ]
