# Generated by Django 2.0.13 on 2019-03-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0025_auto_20190326_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='seen_by_dr',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='specialist_doctor',
        ),
    ]
