# Generated by Django 2.0.13 on 2019-03-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0026_auto_20190326_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherfields',
            name='full_pul_fun_test',
        ),
    ]
