# Generated by Django 2.0.13 on 2019-03-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0027_remove_otherfields_full_pul_fun_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinpricktest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='skinpricktest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='skinpricktest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SkinPrickTest',
        ),
        migrations.RemoveField(
            model_name='details',
            name='other_clinic_site',
        ),
        migrations.RemoveField(
            model_name='details',
            name='site_of_clinic',
        ),
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='month_finished_exposure',
        ),
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='month_started_exposure',
        ),
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='year_finished_exposure',
        ),
    ]
