# Generated by Django 2.0.13 on 2020-02-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0027_remove_otherfields_full_pul_fun_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='referral_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
