# Generated by Django 2.0.13 on 2019-03-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0028_auto_20190328_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='has_asthma',
        ),
        migrations.RemoveField(
            model_name='details',
            name='has_eczema',
        ),
        migrations.RemoveField(
            model_name='details',
            name='has_hayfever',
        ),
        migrations.RemoveField(
            model_name='details',
            name='is_smoker',
        ),
        migrations.RemoveField(
            model_name='details',
            name='previous_atopic_disease',
        ),
        migrations.RemoveField(
            model_name='details',
            name='smokes_per_day',
        ),
    ]
