# Generated by Django 2.0.13 on 2019-03-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0029_move_history_fields_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='exposures',
        ),
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='year_started_exposure',
        ),
    ]
