# Generated by Django 2.0.13 on 2019-03-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0030_move_exposure_fields_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='date_referral_received',
        ),
        migrations.RemoveField(
            model_name='details',
            name='geographical_area',
        ),
        migrations.RemoveField(
            model_name='details',
            name='geographical_area_other',
        ),
        migrations.RemoveField(
            model_name='details',
            name='referral_disease',
        ),
        migrations.RemoveField(
            model_name='details',
            name='referral_type',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='referral',
        ),
    ]
