# Generated by Django 2.0.13 on 2019-03-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0031_move_referral_fields_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='fire_service_applicant',
        ),
    ]
