# Generated by Django 2.0.13 on 2019-03-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0032_move_firefighter_to_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='suspectoccupationalcategory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='otherfields',
            name='occupation_other',
        ),
        migrations.DeleteModel(
            name='SuspectOccupationalCategory',
        ),
    ]
