# Generated by Django 2.0.13 on 2019-03-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0033_move_employment_fields_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='details',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='details',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
