# Generated by Django 2.0.13 on 2019-03-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0034_remove_details_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticasthma',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='diagnosticasthma',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosticasthma',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='diagnosticrhinitis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='diagnosticrhinitis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosticrhinitis',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DiagnosticAsthma',
        ),
        migrations.DeleteModel(
            name='DiagnosticRhinitis',
        ),
    ]
