- name: drop the database
  become: true
  become_user: postgres
  postgresql_db:
    name={{ DB_NAME }}
    encoding='UTF-8'
    owner={{ DB_USER }}
    template=template0
    state=absent

- name: create a database
  become: true
  become_user: postgres
  postgresql_db:
    name={{ DB_NAME }}
    encoding='UTF-8'
    owner={{ DB_USER }}
    template=template0

- name: Restore the server from a bucket
  command: "{{ VIRTUALENV_PATH }}/bin/python scripts/restore.py {{ DB_NAME }} {{ DB_USER }} {{ S3_BUCKET_NAME }} {{ RESTORE_BACKUP_S3_KEY }} scripts/s3_secret"
  args:
      chdir: "{{ PROJECT_PATH }}"

- name: Run Django database migrations
  args:
    chdir: "{{ PROJECT_PATH}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py migrate"

- name: Create singletons
  args:
    chdir: "{{ PROJECT_PATH}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py create_singletons"

- name: Load lookuplists
  args:
    chdir: "{{ PROJECT_PATH}}"
  command: "{{ VIRTUALENV_PATH }}/bin/python manage.py load_lookup_lists"
