# Deploy prod is like deploy but sets up backups
---
- name: Things you want on servers generally
  become: true
  user: ubuntu
  hosts: prod_webserver
  gather_facts: no
  roles:
    - setup_server

- name: Make the server capable of running a standard database
  become: true
  user: ubuntu
  hosts: prod_webserver
  roles:
    - setup_db

- name: Set up our project
  user: ubuntu
  hosts: prod_webserver
  roles:
    - setup_rbhl

- name: Set up AWS
  user: ubuntu
  hosts: prod_webserver
  roles:
    - setup_aws

- name: Deploy project
  user: ubuntu
  hosts: prod_webserver
  roles:
    - deploy_rbhl
  vars:
    DEV: 0
    DOMAIN: indigo-rbht.openhealthcare.org.uk

- name: Set up backups
  user: ubuntu
  hosts: prod_webserver
  roles:
    - setup_backups

- name: Restore
  user: ubuntu
  hosts: prod_webserver
  roles:
    - restore
    - restart
