# Generated by Django 2.0.13 on 2020-06-02 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronchialChallengeSubstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BronchialTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('test_num', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Inconclusive', 'Inconclusive')], default='', max_length=256)),
                ('response_type', models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('Dual', 'Dual'), ('Late', 'Late'), ('Early', 'Early'), ('Other', 'Other')], default='Immediate', max_length=256)),
                ('last_exposed', models.DateTimeField(blank=True, null=True)),
                ('duration_exposed', models.TextField(blank=True, default='')),
                ('date', models.DateField(blank=True, null=True)),
                ('baseline_pc20', models.CharField(blank=True, default='', max_length=256)),
                ('lowest_pc20', models.CharField(blank=True, default='', max_length=256)),
                ('substance_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_bronchialtest_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('substance_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.BronchialChallengeSubstance')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_bronchialtest_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OtherInvestigations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('test', models.CharField(blank=True, choices=[('CT chest scan', 'CT chest scan'), ('Full lung function', 'Full lung function')], default='', max_length=256)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_otherinvestigations_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_otherinvestigations_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SkinPrickTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('antihistimines', models.NullBooleanField()),
                ('substance', models.TextField(blank=True, default='', verbose_name='SPT')),
                ('wheal', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_skinpricktest_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_skinpricktest_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Spirometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('date', models.DateField(blank=True, null=True)),
                ('fev_1', models.FloatField(blank=True, null=True, verbose_name='FEV 1')),
                ('fev_1_post_ventolin', models.FloatField(blank=True, null=True, verbose_name='FEV post ventolin')),
                ('fev_1_percentage_predicted', models.IntegerField(blank=True, null=True, verbose_name='FEV 1 % predicted')),
                ('fvc', models.FloatField(blank=True, null=True, verbose_name='FVC')),
                ('fvc_post_ventolin', models.FloatField(blank=True, null=True, verbose_name='FVC post ventolin')),
                ('fvc_percentage_predicted', models.IntegerField(blank=True, null=True, verbose_name='FVC % predicted')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_spirometry_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_spirometry_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='bronchialchallengesubstance',
            unique_together={('code', 'system')},
        ),
    ]
