# Generated by Django 2.0.13 on 2020-06-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronchialtest',
            name='baseline_pc20',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Baseline PC20'),
        ),
        migrations.AlterField(
            model_name='bronchialtest',
            name='lowest_pc20',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Lowest PC20'),
        ),
    ]
