# Generated by Django 2.0.13 on 2020-06-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20200619_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronchialtest',
            name='test_num',
        ),
    ]
