# Generated by Django 2.0.13 on 2020-06-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_bronchialtest_test_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherinvestigations',
            old_name='comments',
            new_name='details',
        ),
    ]
