# Generated by Django 2.0.13 on 2020-06-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20200623_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skinpricktest',
            old_name='antihistimines',
            new_name='antihistamines',
        ),
    ]
