# Generated by Django 2.0.13 on 2020-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20200623_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirometry',
            name='fev_1_percentage_predicted',
            field=models.IntegerField(blank=True, null=True, verbose_name='FEV 1 predicted'),
        ),
        migrations.AlterField(
            model_name='spirometry',
            name='fvc_percentage_predicted',
            field=models.IntegerField(blank=True, null=True, verbose_name='FVC predicted'),
        ),
    ]
