# Generated by Django 2.0.13 on 2020-06-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20200624_1805'),
        ('lab', '0005_auto_20200625_1129'),
    ]

    operations = [
    ]
