# Generated by Django 2.0.13 on 2020-09-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0038_auto_20191206_1449'),
        ('lab', '0006_merge_20200626_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BloodBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('reference_number', models.CharField(blank=True, max_length=256, null=True)),
                ('sample_received', models.DateField(blank=True, null=True)),
                ('blood_number', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_taken', models.DateTimeField(blank=True, null=True)),
                ('store', models.NullBooleanField()),
                ('assay_number', models.CharField(blank=True, max_length=200, null=True)),
                ('assay_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('ImmunoCAP', 'ImmunoCAP'), ('UniCAP', 'UniCAP'), ('CAP', 'CAP'), ('RAST', 'RAST'), ('CAP & RAST', 'CAP & RAST'), ('RAST & UniCAP', 'RAST & UniCAP'), ('PRECIPITINS', 'PRECIPITINS')], max_length=256, null=True)),
                ('antigen_type', models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('BESPOKE', 'BESPOKE')], max_length=256, null=True)),
                ('antigen_date', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('report_submitted', models.DateField(blank=True, null=True)),
                ('information', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_bloodbook_subrecords', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_bloodbook_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BloodBookResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, max_length=200, null=True)),
                ('antigen_number', models.CharField(blank=True, max_length=200, null=True)),
                ('kul', models.CharField(blank=True, max_length=200, null=True, verbose_name='KU/L')),
                ('ige_class', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=200, null=True, verbose_name='IgE Class')),
                ('rast', models.FloatField(blank=True, null=True, verbose_name='RAST %B')),
                ('precipitin', models.CharField(blank=True, choices=[('-ve', '-ve'), ('+ve', '+ve'), ('Weak +ve', 'Weak +ve'), ('++ve', '++ve')], max_length=200, null=True, verbose_name='Precipitin')),
                ('igg_mg', models.FloatField(blank=True, null=True, verbose_name='mg/L')),
                ('igg_class', models.IntegerField(blank=True, null=True, verbose_name='IgG class')),
                ('allergen_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('allergen_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Allergen')),
                ('blood_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.BloodBook')),
            ],
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='allergen',
            unique_together={('code', 'system')},
        ),
    ]
