# Generated by Django 2.2.16 on 2020-12-15 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab', '0007_auto_20201202_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('system', models.CharField(blank=True, max_length=255, null=True, verbose_name='System')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Version')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('code', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('system', models.CharField(blank=True, max_length=255, null=True, verbose_name='System')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='Version')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('code', 'system')},
            },
        ),
        migrations.CreateModel(
            name='Bloods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
                ('consistency_token', models.CharField(max_length=8, verbose_name='Consistency Token')),
                ('blood_date', models.DateField(blank=True, null=True, verbose_name='Sample received')),
                ('blood_number', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, choices=[('ImmunoCAP', 'ImmunoCAP'), ('RAST', 'RAST'), ('RAST Score', 'RAST Score'), ('Precipitins', 'Precipitins')], max_length=200, null=True)),
                ('blood_collected', models.CharField(blank=True, max_length=200, null=True, verbose_name='EDTA blood collected')),
                ('date_dna_extracted', models.CharField(blank=True, max_length=200, null=True)),
                ('assayno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assay number')),
                ('assay_date', models.DateField(blank=True, null=True)),
                ('blood_taken', models.DateField(blank=True, null=True)),
                ('blood_tm', models.CharField(blank=True, max_length=200, null=True)),
                ('report_dt', models.DateField(blank=True, null=True, verbose_name='Report date')),
                ('report_st', models.DateField(blank=True, null=True, verbose_name='Report submitted')),
                ('store', models.NullBooleanField()),
                ('antigen_date', models.DateField(blank=True, null=True)),
                ('antigen_type', models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('BESPOKE', 'BESPOKE')], max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('batches', models.TextField(blank=True, null=True)),
                ('room', models.TextField(blank=True, null=True)),
                ('freezer', models.TextField(blank=True, null=True)),
                ('shelf', models.TextField(blank=True, null=True)),
                ('tray', models.TextField(blank=True, null=True)),
                ('vials', models.TextField(blank=True, null=True)),
                ('exposure_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_bloods_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('exposure_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Exposure')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient', verbose_name='Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lab_bloods_subrecords', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BloodResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('phadia_test_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Antigen number')),
                ('kul', models.CharField(blank=True, max_length=200, null=True, verbose_name='KU/L')),
                ('klass', models.IntegerField(blank=True, null=True, verbose_name='IgE Class')),
                ('rast', models.FloatField(blank=True, null=True)),
                ('rast_score', models.FloatField(blank=True, null=True, verbose_name='RAST score')),
                ('precipitin', models.CharField(blank=True, choices=[('-ve', '-ve'), ('+ve', '+ve'), ('Weak +ve', 'Weak +ve'), ('++ve', '++ve')], max_length=200, null=True)),
                ('igg', models.FloatField(blank=True, null=True)),
                ('iggclass', models.IntegerField(blank=True, null=True, verbose_name='IgG Class')),
                ('allergen_ft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('allergen_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Allergen')),
                ('bloods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Bloods')),
            ],
        ),
    ]
