# Generated by Django 2.0.13 on 2020-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20200922_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergenresult',
            name='antigen_date',
        ),
        migrations.AddField(
            model_name='bloodbook',
            name='antigen_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
