# Generated by Django 2.0.13 on 2020-09-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20200922_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbook',
            name='exposure_fk',
        ),
        migrations.RemoveField(
            model_name='bloodbook',
            name='exposure_ft',
        ),
    ]
