# Generated by Django 2.2.16 on 2021-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_allergen_bloodresult_bloods_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloods',
            name='authorised_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
