# Generated by Django 2.0.13 on 2020-09-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20200924_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllergenResult',
            new_name='BloodBookResult',
        ),
    ]
