# Generated by Django 2.2.16 on 2021-02-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_bloodresult_comment'),
        ('lab', '0010_auto_20210201_1225'),
    ]

    operations = [
    ]
