# Generated by Django 2.2.16 on 2021-02-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_merge_20210204_1218'),
        ('lab', '0011_merge_20210205_1748'),
    ]

    operations = [
    ]
