# Generated by Django 2.2.16 on 2021-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_merge_20210207_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodresult',
            name='stimulation_index_day_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodresult',
            name='stimulation_index_day_7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloods',
            name='method',
            field=models.CharField(blank=True, choices=[('ImmunoCAP', 'ImmunoCAP'), ('RAST', 'RAST'), ('RAST Score', 'RAST Score'), ('Precipitins', 'Precipitins'), ('Lymphocyte Proliferation Test', 'Lymphocyte Proliferation Test')], max_length=200, null=True),
        ),
    ]
