# Generated by Django 2.2.16 on 2021-02-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_merge_20210207_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodresult',
            name='comment',
        ),
    ]
