# Generated by Django 2.2.16 on 2021-06-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_remove_bloodresult_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='igg',
            field=models.FloatField(blank=True, null=True, verbose_name='IgG'),
        ),
        migrations.AlterField(
            model_name='bloodresult',
            name='rast',
            field=models.FloatField(blank=True, null=True, verbose_name='RAST'),
        ),
    ]
