# Generated by Django 2.2.16 on 2021-02-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_merge_20210205_1808'),
        ('lab', '0011_merge_20210207_1817'),
    ]

    operations = [
    ]
