# Generated by Django 2.2.16 on 2021-02-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_remove_bloodresult_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloods',
            options={'verbose_name_plural': 'Bloods'},
        ),
    ]
