# Generated by Django 2.2.16 on 2021-02-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_merge_20210207_1922'),
        ('lab', '0012_auto_20210208_1703'),
    ]

    operations = [
    ]
