# Generated by Django 2.2.16 on 2021-11-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0040_auto_20201007_1346'),
        ('lab', '0014_remove_bloodresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloods',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.Episode'),
        ),
    ]
