# Generated by Django 2.2.16 on 2022-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_remove_bloodresult_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodresult',
            name='precipitin',
            field=models.CharField(blank=True, choices=[('-ve', '-ve'), ('+ve', '+ve'), ('Weak +ve', 'Weak +ve'), ('++ve', '++ve')], max_length=200, null=True, verbose_name='Precipitin'),
        ),
    ]
