# Generated by Django 2.2.16 on 2022-05-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_auto_20220511_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloods',
            name='employment',
        ),
    ]
