# Generated by Django 2.2.16 on 2021-11-26 13:50

from django.db import migrations


def forwards(apps, schema_editor):
	pass


def backwards(apps, schema_editor):
	pass


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_remove_bloodresult_result'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
