# Generated by Django 2.2.16 on 2022-05-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_create_multiple_episodes'),
        ('lab', '0015_auto_20220511_1354'),
    ]

    operations = [
    ]
