# Generated by Django 2.2.16 on 2023-08-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_remove_bloods_date_dna_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloods',
            name='sample_destroyed',
            field=models.NullBooleanField(),
        ),
    ]
