# Generated by Django 2.2.16 on 2025-09-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_bloods_sample_destroyed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloods',
            name='antigen_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('BESPOKE', 'BESPOKE'), ('BESPOKE & STANDARD', 'BESPOKE & STANDARD')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bloods',
            name='method',
            field=models.CharField(blank=True, choices=[('ImmunoCAP', 'ImmunoCAP'), ('RAST', 'RAST'), ('RAST Score', 'RAST Score'), ('Precipitins', 'Precipitins'), ('ImmunoCAP & RAST', 'ImmunoCAP & RAST'), ('ImmunoCAP & RAST Score', 'ImmunoCAP & RAST Score'), ('ImmunoCAP, RAST & RAST Score', 'ImmunoCAP, RAST & RAST Score'), ('RAST & RAST Score', 'RAST & RAST Score')], max_length=200, null=True),
        ),
    ]
