# Generated by Django 2.0.13 on 2020-09-04 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opal', '0038_auto_20191206_1449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('allergen', models.CharField(blank=True, max_length=200, null=True)),
                ('antigen_no', models.CharField(blank=True, max_length=200, null=True)),
                ('kul', models.CharField(blank=True, max_length=200, null=True, verbose_name='KU/L')),
                ('ige_class', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=200, null=True, verbose_name='IgE Class')),
                ('rast', models.FloatField(blank=True, null=True, verbose_name='RAST %B')),
                ('precipitin', models.CharField(blank=True, choices=[('-ve', '-ve'), ('+ve', '+ve'), ('Weak +ve', 'Weak +ve')], max_length=200, null=True, verbose_name='Precipitin')),
                ('igg_mg', models.FloatField(blank=True, null=True, verbose_name='mg/L')),
                ('igg_class', models.IntegerField(blank=True, null=True, verbose_name='IgG class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blood_book_allergenresult_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blood_book_allergenresult_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Antigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('assay_no', models.CharField(blank=True, max_length=200, null=True)),
                ('assay_date', models.DateField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('ImmunoCAP', 'ImmunoCAP'), ('UniCAP', 'UniCAP'), ('CAP', 'CAP'), ('RAST', 'RAST'), ('CAP & RAST', 'CAP & RAST'), ('RAST & UniCAP', 'RAST & UniCAP'), ('PRECIPITINS', 'PRECIPITINS')], max_length=256, null=True)),
                ('antigen_date', models.DateField(blank=True, null=True)),
                ('antigen_type', models.CharField(blank=True, choices=[('STANDARD', 'STANDARD'), ('BESPOKE', 'BESPOKE')], max_length=256, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blood_book_antigen_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blood_book_antigen_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('details', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blood_book_note_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blood_book_note_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('blood_date', models.DateField(blank=True, null=True)),
                ('blood_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_dna_extracted', models.CharField(blank=True, max_length=200, null=True)),
                ('blood_taken', models.DateField(blank=True, null=True)),
                ('blood_tm', models.DateField(blank=True, null=True)),
                ('report_dt', models.DateField(blank=True, null=True)),
                ('report_st', models.DateField(blank=True, null=True)),
                ('store', models.NullBooleanField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blood_book_specimen_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_blood_book_specimen_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
