# Generated by Django 2.0.9 on 2019-01-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0003_auto_20190123_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='date_refferal_received',
            new_name='date_referral_received',
        ),
    ]
