# Generated by Django 2.0.9 on 2019-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0005_auto_20190129_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniclog',
            options={'verbose_name': 'Clinic log'},
        ),
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'Contact details'},
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='date_of_followup',
            field=models.DateField(blank=True, null=True, verbose_name='Date of follow up'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='diagnosis_made',
            field=models.NullBooleanField(verbose_name='Diagnosis made'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='follow_up_planned',
            field=models.NullBooleanField(verbose_name='Follow up planned'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='histamine_attendance',
            field=models.NullBooleanField(verbose_name='Histamine attendance'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='histamine_date',
            field=models.DateField(blank=True, null=True, verbose_name='Histamine date'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='immunology_oem',
            field=models.NullBooleanField(verbose_name='Immunology OEM'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='lung_function',
            field=models.NullBooleanField(verbose_name='Lung function'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='lung_function_attendance',
            field=models.NullBooleanField(verbose_name='Lung function attendance'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='lung_function_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lung function date'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='other_gp_info',
            field=models.NullBooleanField(verbose_name='Other GP info'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='other_hospital_info',
            field=models.NullBooleanField(verbose_name='Other hospital info'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='other_oh_info',
            field=models.NullBooleanField(verbose_name='Other OH info'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='other_rbh_bloods',
            field=models.NullBooleanField(verbose_name='Other RBH bloods'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='peak_flow',
            field=models.NullBooleanField(verbose_name='Peak flow'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='seen_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seen by'),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='work_samples',
            field=models.NullBooleanField(verbose_name='Work samples'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='oh_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OH provider'),
        ),
    ]
