# Generated by Django 2.0.9 on 2019-01-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0006_auto_20190129_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliniclog',
            old_name='clinicdate',
            new_name='clinic_date',
        ),
    ]
