# Generated by Django 2.0.9 on 2019-01-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0006_auto_20190129_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='date_first_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first appointment'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_first_contact',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first contact'),
        ),
    ]
