# Generated by Django 2.0.9 on 2019-02-13 19:21

from django.db import migrations

# This migration used to add the CAN SEE PEAK FLOW Role however
# that role no longer exists. Peak flow is available for everyone.


def forwards(apps, schema_editor):
    pass


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0007_auto_20190130_1619'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
