# Generated by Django 2.0.9 on 2019-02-13 19:21

from django.db import migrations
from rbhl import constants


def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.create(name=constants.CAN_SEE_PEAK_FLOW)


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name=constants.CAN_SEE_PEAK_FLOW).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0007_auto_20190130_1619'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
