# Generated by Django 2.0.9 on 2019-02-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0008_auto_20190207_2125'),
        ('rbhl', '0007_auto_20190130_1339'),
        ('rbhl', '0008_auto_20190213_1921'),
    ]

    operations = [
    ]
