# Generated by Django 2.0.9 on 2019-02-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0007_auto_20190130_1339'),
        ('rbhl', '0008_auto_20190207_2125'),
    ]

    operations = [
    ]
