# Generated by Django 2.0.9 on 2019-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0009_merge_20190220_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height(cm)'),
        ),
    ]
