# Generated by Django 2.0.9 on 2019-02-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0010_auto_20190226_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='firefighter',
        ),
        migrations.AddField(
            model_name='employment',
            name='firefighter',
            field=models.NullBooleanField(),
        ),
    ]
