# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0010_cliniclog_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclog',
            name='histamine',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='histamine_attendance',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='histamine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='immunology_oem',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='lung_function',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='lung_function_attendance',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='lung_function_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='other_gp_info',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='other_hospital_info',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='other_oh_info',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='other_rbh_bloods',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='peak_flow',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='work_samples',
            field=models.NullBooleanField(),
        ),
    ]
