# Generated by Django 2.0.9 on 2019-02-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0011_peakexpiratoryflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peakflowday',
            options={'ordering': ['day_num']},
        ),
    ]
