# Generated by Django 2.0.13 on 2019-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0011_auto_20190226_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakflowday',
            name='work_day',
            field=models.BooleanField(default=False),
        ),
    ]
