# Generated by Django 2.0.13 on 2019-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0011_auto_20190226_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peakflowday',
            options={'ordering': ['day_num']},
        ),
        migrations.AddField(
            model_name='demographics',
            name='height',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Height(cm)'
            ),
        ),
    ]
