# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0012_auto_20181108_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakflowday',
            name='day_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
