# Generated by Django 2.0.13 on 2019-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0012_demographics_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
