# Generated by Django 2.0.13 on 2019-03-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0012_demographics_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.TextField(blank=True, null=True, verbose_name='Type of Referral'),
        ),
    ]
