# Generated by Django 2.0.13 on 2019-03-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0013_auto_20190320_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peakflowday',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='peakflowday',
            name='work_start',
        ),
    ]
