# Generated by Django 2.0.13 on 2019-03-27 13:29

from django.db import migrations

from rbhl import constants


def add_can_see_extra_fields(apps, schema_editor):
    Role = apps.get_model("opal", "Role")
    Role.objects.create(name=constants.CAN_SEE_EXTRA_FIELDS)


def remove_can_see_extra_fields(apps, schema_editor):
    Role = apps.get_model("opal", "Role")
    Role.objects.filter(name=constants.CAN_SEE_EXTRA_FIELDS).delete()


class Migration(migrations.Migration):

    dependencies = [("rbhl", "0013_referral_referral_type")]

    operations = [
        migrations.RunPython(
            add_can_see_extra_fields, remove_can_see_extra_fields
        )
    ]
