# Generated by Django 2.0.13 on 2019-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0014_auto_20190812_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclog',
            name='seen_by',
            field=models.CharField(
                blank=True, default='',
                max_length=100,
                verbose_name='Seen by'
            ),
        ),
    ]
