# Generated by Django 2.0.13 on 2019-03-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0014_auto_20190320_1849'),
        ('rbhl', '0012_demographics_height'),
    ]

    operations = [
    ]
