# Generated by Django 2.0.13 on 2019-03-28 09:46

import django.db.models.deletion
import opal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opal", "0037_auto_20181114_1445"),
        ("rbhl", "0014_auto_20190327_1329"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                ("atopic_disease", models.TextField(blank=True, null=True)),
                ("has_asthma", models.NullBooleanField()),
                ("has_hayfever", models.NullBooleanField()),
                ("has_eczema", models.NullBooleanField()),
                ("is_smoker", models.TextField(blank=True, null=True)),
                ("smokes_per_day", models.IntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rbhl_history_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opal.Patient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_rbhl_history_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        )
    ]
