# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0014_peakflowday_trial_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peakflowday',
            name='work_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peakflowday',
            name='work_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
