# Generated by Django 2.0.13 on 2019-09-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0015_auto_20190814_0854'),
        ('rbhl', '0015_merge_20190321_0943'),
    ]

    operations = [
    ]
