# Generated by Django 2.0.13 on 2020-01-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0016_merge_20190902_1207'),
        ('rbhl', '0014_auto_20190327_1329'),
    ]

    operations = [
    ]
