# Generated by Django 2.0.13 on 2019-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rbhl", "0016_add_exposure_model")]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="disease",
            field=models.TextField(
                blank=True, null=True, verbose_name="Referral disease"
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="geographical_area",
            field=models.TextField(
                blank=True, null=True, verbose_name="Geographical Area"
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reason for Referral"
            ),
        ),
    ]
