# Generated by Django 2.0.13 on 2020-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0016_merge_20190902_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclog',
            name='outstanding_tests_required',
            field=models.BooleanField(default=False),
        ),
    ]
