# Generated by Django 2.0.13 on 2019-03-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0017_move_referral_fields_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employment_is_suspect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='is_currently_employed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='suspect_occupational_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
