# Generated by Django 2.0.13 on 2020-03-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('rbhl', '0017_importedfrompreviousdatabase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peakflowday',
            unique_together={('day_num', 'trial_num', 'episode')},
        ),
    ]
