# Generated by Django 2.0.13 on 2020-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0017_merge_20200122_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclog',
            name='seen_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Seen by'),
        ),
    ]
