# Generated by Django 2.0.13 on 2019-03-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0018_move_employment_fields_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisasthma',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='diagnosisasthma',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='diagnosisasthma',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='diagnosisrhinitis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='diagnosisrhinitis',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='diagnosisrhinitis',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='DiagnosisAsthma',
        ),
        migrations.DeleteModel(
            name='DiagnosisRhinitis',
        ),
    ]
