# Generated by Django 2.0.13 on 2020-03-26 14:55

from django.db import migrations
from rbhl import constants


def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.create(name=constants.CAN_SEE_TRIALS_FROM_PEAK_FLOW_DB)


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name=constants.CAN_SEE_TRIALS_FROM_PEAK_FLOW_DB).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0018_auto_20200326_1448'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
