# Generated by Django 2.0.13 on 2019-03-29 14:19

import django.db.models.deletion
import opal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opal", "0037_auto_20181114_1445"),
        ("rbhl", "0019_remove_diagnosis_asthma_and_rhinitis_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportingDiagnosis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(blank=True, null=True)),
                ("consistency_token", models.CharField(max_length=8)),
                (
                    "type",
                    models.TextField(
                        choices=[("asthma", "Asthma"), ("rhinitis", "Rhinitis")]
                    ),
                ),
                ("is_work_exacerbated", models.NullBooleanField()),
                ("is_irritant_induced", models.NullBooleanField()),
                ("is_caused_by_sensitisation", models.NullBooleanField()),
                ("sensitising_agent", models.TextField(blank=True, null=True)),
                ("is_non_occupational", models.NullBooleanField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rbhl_supportingdiagnosis_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opal.Episode",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_rbhl_supportingdiagnosis_subrecords",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
            bases=(
                opal.models.UpdatesFromDictMixin,
                opal.models.ToDictMixin,
                models.Model,
            ),
        )
    ]
