# Generated by Django 2.0.13 on 2020-03-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('rbhl', '0019_auto_20200311_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupational_lung_database', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opal.Patient')),
            ],
        ),
    ]
