# Generated by Django 2.0.13 on 2020-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0018_auto_20200122_1545'),
        ('rbhl', '0019_auto_20200326_1455'),
    ]

    operations = [
    ]
