# Generated by Django 2.0.13 on 2020-05-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0020_auto_20200511_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
    ]
