# Generated by Django 2.0.13 on 2020-06-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0021_auto_20200610_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliniclog',
            name='atopic',
        ),
        migrations.RemoveField(
            model_name='cliniclog',
            name='no_appreciable_disease',
        ),
        migrations.AlterField(
            model_name='employment',
            name='firefighter',
            field=models.NullBooleanField(verbose_name='Firefighter applicant'),
        ),
    ]
