# Generated by Django 2.0.13 on 2020-04-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        ('rbhl', '0021_auto_20200430_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_type',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.ReferralType'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
