# Generated by Django 2.0.13 on 2020-05-11 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbhl', '0021_auto_20200511_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeographicalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PresentingComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RbhlDiagnosticTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('antihistimines', models.NullBooleanField()),
                ('skin_prick_test', models.NullBooleanField()),
                ('atopic', models.TextField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Dermatographic', 'Dermatographic')], null=True)),
                ('specific_skin_prick', models.NullBooleanField()),
                ('immunology_oem', models.NullBooleanField(verbose_name='Immunology OEM')),
                ('fev_1', models.FloatField(blank=True, null=True, verbose_name='FEV1')),
                ('fev_1_post_ventolin', models.FloatField(blank=True, null=True, verbose_name='FEV1 post Ventolin')),
                ('fev_1_percentage_protected', models.IntegerField(blank=True, null=True, verbose_name='FEV1 predicted %')),
                ('fvc', models.FloatField(blank=True, null=True, verbose_name='FVC')),
                ('fvc_post_ventolin', models.FloatField(blank=True, null=True, verbose_name='FVC post Ventolin')),
                ('fvc_percentage_protected', models.IntegerField(blank=True, null=True, verbose_name='FVC predicted %')),
                ('ct_chest_scan', models.NullBooleanField(verbose_name='CT chest scan')),
                ('ct_chest_scan_date', models.DateField(blank=True, null=True, verbose_name='CT chest scan date')),
                ('full_lung_function', models.NullBooleanField()),
                ('full_lung_function_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_rbhldiagnostictesting_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_rbhldiagnostictesting_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic testing',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReferralDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('smoker', models.CharField(blank=True, choices=[('Currently', 'Currently'), ('Ex-smoker', 'Ex-smoker'), ('Never', 'Never')], max_length=256, null=True)),
                ('cigerettes_per_day', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_socialhistory_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_socialhistory_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='clinic_site',
            field=models.CharField(blank=True, default='OCLD', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='diagnosis_outcome_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='presenting_complaint_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='referred_to',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='employed_in_suspect_occupation',
            field=models.CharField(blank=True, choices=[('Yes-employed in suspect occupation', 'Yes-employed in suspect occupation'), ('Yes', 'Yes'), ('Yes-other occupation', 'Yes-other occupation'), ('No', 'No')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_category_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='exposures',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employment',
            name='job_title_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='geographical_area_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_disease_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_reason_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opal.ReferralType'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='date_of_followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='seen_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='referralreason',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='referraldisease',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='presentingcomplaint',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='geographicalarea',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='employmentcategory',
            unique_together={('code', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisoutcome',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='diagnosis_outcome_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.DiagnosisOutcome'),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='presenting_complaint_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.PresentingComplaint'),
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.EmploymentCategory'),
        ),
        migrations.AddField(
            model_name='employment',
            name='job_title_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.JobTitle'),
        ),
        migrations.AddField(
            model_name='referral',
            name='geographical_area_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.GeographicalArea'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_disease_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.ReferralDisease'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_reason_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.ReferralReason'),
        ),
    ]
