# Generated by Django 2.0.13 on 2020-05-01 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0022_auto_20200430_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeographicArea',
            new_name='GeographicalArea',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='geographic_area_fk',
            new_name='geographical_area_fk',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='geographic_area_ft',
            new_name='geographical_area_ft',
        ),
    ]
