# Generated by Django 2.0.13 on 2020-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0022_auto_20200511_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
