# Generated by Django 2.0.13 on 2020-04-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        ('opal', '0037_auto_20181114_1445'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbhl', '0023_auto_20200428_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RbhlDiagnosticTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('antihistimines', models.NullBooleanField()),
                ('skin_prick_test', models.NullBooleanField()),
                ('atopic', models.TextField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Dermatographic', 'Dermatographic')], null=True)),
                ('specific_skin_prick', models.NullBooleanField()),
                ('immunology_oem', models.NullBooleanField(verbose_name='Immunology OEM')),
                ('fev_1', models.FloatField(blank=True, null=True)),
                ('fev_1_post_ventolin', models.FloatField(blank=True, null=True)),
                ('fev_1_percentage_protected', models.IntegerField(blank=True, null=True)),
                ('fvc', models.FloatField(blank=True, null=True)),
                ('fvc_post_ventolin', models.FloatField(blank=True, null=True)),
                ('fvc_percentage_protected', models.IntegerField(blank=True, null=True)),
                ('ct_chest_scan', models.NullBooleanField()),
                ('ct_chest_scan_date', models.DateTimeField(blank=True, null=True)),
                ('full_lung_function', models.NullBooleanField()),
                ('full_lung_function_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_rbhldiagnostictesting_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_rbhldiagnostictesting_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic testing',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='GeographicArea',
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_category_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employercategory',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='employment',
            name='employment_category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.EmployerCategory'),
        ),
    ]
