# Generated by Django 2.0.13 on 2020-06-17 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('rbhl', '0023_asthmadetails_diagnosis_rhinitisdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('smoker', models.CharField(blank=True, choices=[('Currently', 'Currently'), ('Ex-smoker', 'Ex-smoker'), ('Never', 'Never')], max_length=256, null=True)),
                ('cigerettes_per_day', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_socialhistory_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_socialhistory_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='category',
            field=models.CharField(blank=True, choices=[('asthma', 'asthma'), ('rhinitis', 'rhinitis'), ('chronic_air_flow_limitation', 'chronic_air_flow_limitation'), ('NAD', 'NAD'), ('malignancy', 'malignancy'), ('benign_pleural_disease', 'benign_pleural_disease'), ('diffuse_lung_disease', 'diffuse_lung_disease'), ('other', 'other')], max_length=256, null=True),
        ),
    ]
