# Generated by Django 2.0.13 on 2020-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0023_contactdetails_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='asthma_options',
            field=models.TextField(blank=True, choices=[('Occupational asthma caused by sensitisation', 'Occupational asthma caused by sensitisation'), ('Exacerbated by work', 'Exacerbated by work'), ('Irritant induced', 'Irritant induced'), ('Non occupational', 'Non occupational')], default=''),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='occupational',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='rhinitis_options',
            field=models.TextField(blank=True, choices=[('Occupational asthma caused by sensitisation', 'Occupational asthma caused by sensitisation'), ('Exacerbated by work', 'Exacerbated by work'), ('Non occupational', 'Non occupational')], default=''),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='sensitivities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
