# Generated by Django 2.0.13 on 2020-05-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0024_auto_20200501_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='socialhistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='job_title_fk',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='job_title_ft',
        ),
        migrations.DeleteModel(
            name='SocialHistory',
        ),
    ]
