# Generated by Django 2.0.13 on 2020-05-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0024_auto_20200514_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rbhldiagnostictesting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rbhldiagnostictesting',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='rbhldiagnostictesting',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='RbhlDiagnosticTesting',
        ),
    ]
