# Generated by Django 2.0.13 on 2020-04-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0024_auto_20200429_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employment',
            name='employed_in_suspect_occupation',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='employment',
            name='exposures',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employment',
            name='job_title_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='ct_chest_scan',
            field=models.NullBooleanField(verbose_name='CT chest scan'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='ct_chest_scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CT chest scan date'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='fev_1',
            field=models.FloatField(blank=True, null=True, verbose_name='FEV1'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='fev_1_percentage_protected',
            field=models.IntegerField(blank=True, null=True, verbose_name='FEV1 predicted %'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='fev_1_post_ventolin',
            field=models.FloatField(blank=True, null=True, verbose_name='FEV1 post Ventolin'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='fvc',
            field=models.FloatField(blank=True, null=True, verbose_name='FVC'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='fvc_percentage_protected',
            field=models.IntegerField(blank=True, null=True, verbose_name='FVC predicted %'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='fvc_post_ventolin',
            field=models.FloatField(blank=True, null=True, verbose_name='FVC post Ventolin'),
        ),
        migrations.AlterUniqueTogether(
            name='jobtitle',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='employment',
            name='job_title_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.JobTitle'),
        ),
    ]
