# Generated by Django 2.0.13 on 2020-05-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('rbhl', '0025_auto_20200514_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asthma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('trigger', models.CharField(blank=True, choices=[('Occupational caused by sensitisation', 'Occupational caused by sensitisation'), ('Exacerbated by work', 'Exacerbated by work'), ('Irritant induced', 'Irritant induced'), ('Non occupational', 'Non occupational')], max_length=256, null=True)),
                ('sensitivities', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_asthma_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_asthma_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Rhinitis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('trigger', models.CharField(blank=True, choices=[('Occupational caused by sensitisation', 'Occupational caused by sensitisation'), ('Exacerbated by work', 'Exacerbated by work'), ('Irritant induced', 'Irritant induced'), ('Non occupational', 'Non occupational')], max_length=256, null=True)),
                ('sensitivities', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_rhinitis_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_rhinitis_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='asthmadiagnosis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='asthmadiagnosis',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='asthmadiagnosis',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rhinitisdiagnosis',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rhinitisdiagnosis',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='rhinitisdiagnosis',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AsthmaDiagnosis',
        ),
        migrations.DeleteModel(
            name='RhinitisDiagnosis',
        ),
    ]
