# Generated by Django 2.0.13 on 2020-05-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0025_auto_20200511_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='condition',
        ),
    ]
