# Generated by Django 2.0.13 on 2020-06-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0026_auto_20200618_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='employed_in_suspect_occupation',
        ),
    ]
