# Generated by Django 2.0.13 on 2020-05-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0026_auto_20200514_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicairflowlimitation',
            name='copd',
            field=models.BooleanField(default=False, verbose_name='COPD'),
        ),
        migrations.AlterField(
            model_name='otherinvestigations',
            name='ct_chest_scan',
            field=models.NullBooleanField(verbose_name='CT chest scan'),
        ),
        migrations.AlterField(
            model_name='otherinvestigations',
            name='ct_chest_scan_date',
            field=models.DateField(blank=True, null=True, verbose_name='CT chest scan date'),
        ),
    ]
