# Generated by Django 2.0.13 on 2020-05-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0026_socialhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentingComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='presenting_complaint_ft',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='date_of_followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='diagnosis_made',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='follow_up_planned',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='histamine_attendance',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='histamine_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='lung_function',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='lung_function_attendance',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='lung_function_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='other_hospital_info',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='other_rbh_bloods',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='peak_flow',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='seen_by',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='work_samples',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_of_referral',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_referral_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='presentingcomplaint',
            unique_together={('code', 'system')},
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='presenting_complaint_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbhl.PresentingComplaint'),
        ),
    ]
