# Generated by Django 2.0.13 on 2020-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0026_remove_diagnosis_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_type',
            field=models.CharField(blank=True, choices=[('Asthma', 'Asthma'), ('Rhinitis', 'Rhinitis'), ('Chronic air flow limitation', 'Chronic air flow limitation'), ('Malignancy', 'Malignancy'), ('Diffuse lung disease', 'Diffuse lung disease'), ('Benign plerual disease', 'Benign plerual disease'), ('Other diagnosis', 'Other diagnosis'), ('NAD', 'NAD')], max_length=256, null=True),
        ),
    ]
