# Generated by Django 2.0.13 on 2020-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0027_remove_employment_employed_in_suspect_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employed_in_suspect_occupation',
            field=models.BooleanField(default=False),
        ),
    ]
