# Generated by Django 2.0.13 on 2020-05-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0027_auto_20200514_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronchialtest',
            name='response_type',
            field=models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('Dual', 'Dual'), ('Late', 'Late'), ('Early', 'Early'), ('Other', 'Other')], default='Immediate', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rhinitis',
            name='trigger',
            field=models.CharField(blank=True, choices=[('Occupational caused by sensitisation', 'Occupational caused by sensitisation'), ('Exacerbated by work', 'Exacerbated by work'), ('Non occupational', 'Non occupational')], max_length=256, null=True),
        ),
    ]
