# Generated by Django 2.0.13 on 2020-05-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0037_auto_20181114_1445'),
        ('rbhl', '0028_auto_20200504_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='RbhlDiagnosticTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('antihistimines', models.NullBooleanField()),
                ('skin_prick_test', models.NullBooleanField()),
                ('atopic', models.TextField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Dermatographic', 'Dermatographic')], null=True)),
                ('specific_skin_prick', models.NullBooleanField()),
                ('immunology_oem', models.NullBooleanField(verbose_name='Immunology OEM')),
                ('fev_1', models.FloatField(blank=True, null=True, verbose_name='FEV1')),
                ('fev_1_post_ventolin', models.FloatField(blank=True, null=True, verbose_name='FEV1 post Ventolin')),
                ('fev_1_percentage_protected', models.IntegerField(blank=True, null=True, verbose_name='FEV1 predicted %')),
                ('fvc', models.FloatField(blank=True, null=True, verbose_name='FVC')),
                ('fvc_post_ventolin', models.FloatField(blank=True, null=True, verbose_name='FVC post Ventolin')),
                ('fvc_percentage_protected', models.IntegerField(blank=True, null=True, verbose_name='FVC predicted %')),
                ('ct_chest_scan', models.NullBooleanField(verbose_name='CT chest scan')),
                ('ct_chest_scan_date', models.DateTimeField(blank=True, null=True, verbose_name='CT chest scan date')),
                ('full_lung_function', models.NullBooleanField()),
                ('full_lung_function_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rbhl_rbhldiagnostictesting_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rbhl_rbhldiagnostictesting_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic testing',
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
