# Generated by Django 2.0.13 on 2020-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0028_auto_20200512_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostictest',
            name='condition_fk',
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='condition_ft',
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='date_of_diagnosis',
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='details',
        ),
        migrations.RemoveField(
            model_name='diagnostictest',
            name='provisional',
        ),
    ]
