# Generated by Django 2.0.13 on 2020-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0028_auto_20200515_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nad',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='nad',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='nad',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='skinpricktest',
            name='atopic',
        ),
        migrations.RemoveField(
            model_name='skinpricktest',
            name='immunology_oem',
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='atopic',
            field=models.TextField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Dermatographic', 'Dermatographic')], null=True),
        ),
        migrations.AddField(
            model_name='cliniclog',
            name='no_appreciable_disease',
            field=models.NullBooleanField(verbose_name='NAD'),
        ),
        migrations.DeleteModel(
            name='Nad',
        ),
    ]
