# Generated by Django 2.0.13 on 2020-05-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0029_auto_20200513_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostictest',
            old_name='specifc_skin_prick_test',
            new_name='specific_skin_prick',
        ),
    ]
