# Generated by Django 2.0.13 on 2020-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0029_auto_20200520_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spirometry',
            name='fev_1',
            field=models.FloatField(blank=True, null=True, verbose_name='FEV 1'),
        ),
        migrations.AlterField(
            model_name='spirometry',
            name='fev_1_percentage_predicted',
            field=models.IntegerField(blank=True, null=True, verbose_name='FEV 1 % predicted'),
        ),
        migrations.AlterField(
            model_name='spirometry',
            name='fev_1_post_ventolin',
            field=models.FloatField(blank=True, null=True, verbose_name='FEV post ventolin'),
        ),
        migrations.AlterField(
            model_name='spirometry',
            name='fvc',
            field=models.FloatField(blank=True, null=True, verbose_name='FVC'),
        ),
        migrations.AlterField(
            model_name='spirometry',
            name='fvc_percentage_predicted',
            field=models.IntegerField(blank=True, null=True, verbose_name='FVC post ventolin'),
        ),
        migrations.AlterField(
            model_name='spirometry',
            name='fvc_post_ventolin',
            field=models.FloatField(blank=True, null=True, verbose_name='FVC post ventolin'),
        ),
    ]
