# Generated by Django 2.0.13 on 2020-05-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0029_rbhldiagnostictesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='ct_chest_scan_date',
            field=models.DateField(blank=True, null=True, verbose_name='CT chest scan date'),
        ),
        migrations.AlterField(
            model_name='rbhldiagnostictesting',
            name='full_lung_function_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
