# Generated by Django 2.0.13 on 2020-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0030_auto_20200520_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinespt',
            name='antihistimines',
            field=models.BooleanField(default=False),
        ),
    ]
