# Generated by Django 2.0.13 on 2020-05-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0032_auto_20200526_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routinespt',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='routinespt',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='routinespt',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='specificskinpricktest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specificskinpricktest',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='specificskinpricktest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='RoutineSPT',
        ),
        migrations.DeleteModel(
            name='SpecificSkinPrickTest',
        ),
    ]
