# Generated by Django 2.0.13 on 2020-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0032_auto_20200623_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='category',
            field=models.CharField(blank=True, choices=[('Asthma', 'Asthma'), ('Rhinitis', 'Rhinitis'), ('Chronic air flow limitation', 'Chronic air flow limitation'), ('Malignancy', 'Malignancy'), ('Benign pleural disease', 'Benign pleural disease'), ('Diffuse lung disease', 'Diffuse lung disease'), ('Other', 'Other')], max_length=256, null=True),
        ),
    ]
