# Generated by Django 2.0.13 on 2020-06-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0033_auto_20200623_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliniclog',
            options={'verbose_name': 'Clinic details'},
        ),
    ]
