# Generated by Django 2.0.13 on 2020-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0033_auto_20200505_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='diffuse_lung_disease_occupational',
            field=models.BooleanField(default=False),
        ),
    ]
