# Generated by Django 2.0.13 on 2020-05-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0034_disease_diffuse_lung_disease_occupational'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asthma',
            old_name='occupational',
            new_name='occupational_caused_by_sensitisation',
        ),
        migrations.RenameField(
            model_name='rhinitis',
            old_name='occupational',
            new_name='occupational_caused_by_sensitisation',
        ),
    ]
