# Generated by Django 2.0.13 on 2020-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0036_auto_20200506_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicairflowlimitation',
            name='copd',
            field=models.BooleanField(default=False, verbose_name='COPD'),
        ),
    ]
