# Generated by Django 2.0.13 on 2020-07-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0037_remove_cliniclog_diagnosis_made'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentingComplaint',
        ),
        migrations.RemoveField(
            model_name='cliniclog',
            name='presenting_complaint_fk',
        ),
        migrations.RemoveField(
            model_name='cliniclog',
            name='presenting_complaint_ft',
        ),
    ]
