# Generated by Django 2.0.13 on 2020-05-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0037_auto_20200506_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Height (cm)'),
        ),
    ]
