# Generated by Django 2.0.13 on 2020-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0038_auto_20200702_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='employed_in_suspect_occupation',
            field=models.BooleanField(default=False, verbose_name='‘currently employed in suspect occupation'),
        ),
    ]
