# Generated by Django 2.0.13 on 2020-07-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0039_auto_20200702_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referral_type',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_source',
            field=models.TextField(blank=True, choices=[('GP', 'GP'), ('RBH doctor', 'RBH doctor'), ('Other hospital doctor', 'Other hospital doctor'), ('Occupational health doctor or nurse', 'Occupational health doctor or nurse'), ('Medico legal', 'Medico legal'), ('Self', 'Self'), ('Other', 'Other')], null=True, verbose_name='Referral source'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='employed_in_suspect_occupation',
            field=models.BooleanField(default=False, verbose_name='Currently employed in suspect occupation'),
        ),
    ]
