# Generated by Django 2.0.13 on 2020-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0040_auto_20200702_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='date_referral_received',
            field=models.DateField(blank=True, null=True, verbose_name='Date referral received'),
        ),
    ]
