# Generated by Django 2.0.13 on 2020-07-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0041_auto_20200702_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetails',
            name='email_consent',
            field=models.BooleanField(default=False),
        ),
    ]
