# Generated by Django 2.0.13 on 2020-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0043_setuptwofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='blood_book_ref_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
