# Generated by Django 2.0.13 on 2020-09-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0043_setuptwofactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='reason_for_interaction_fk',
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PatientConsultation',
        ),
    ]
