# Generated by Django 2.0.13 on 2020-11-16 16:08

from django.db import migrations
from rbhl import constants


def forwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.create(name=constants.LAB_USER)


def backwards(apps, schema_editor):
    Role = apps.get_model(
        'opal', 'Role'
    )
    Role.objects.filter(name=constants.LAB_USER).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0044_auto_20200908_1010'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
