# Generated by Django 2.2.16 on 2020-12-10 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0045_auto_20201116_1608'),
        ('rbhl', '0045_auto_20201202_1135'),
    ]

    operations = [
    ]
