# Generated by Django 2.2.16 on 2021-02-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0047_referral_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
