# Generated by Django 2.2.16 on 2021-02-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0048_employment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='notes',
        ),
    ]
