# Generated by Django 2.2.16 on 2021-02-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0049_remove_employment_notes'),
        ('rbhl', '0046_auto_20210121_2023'),
    ]

    operations = [
    ]
