# Generated by Django 2.2.16 on 2021-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0050_merge_20210210_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='ocld',
            field=models.BooleanField(default=True, verbose_name='OCLD'),
        ),
    ]
