# Generated by Django 2.2.16 on 2021-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0052_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclog',
            name='cns',
            field=models.CharField(blank=True, default='', help_text='Clinical nurse specialist', max_length=100, null=True, verbose_name='CNS'),
        ),
    ]
