# Generated by Django 2.2.16 on 2021-07-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0052_fact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='ocld',
            new_name='occld',
        ),
    ]
