# Generated by Django 2.2.16 on 2021-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0053_auto_20210706_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='occld',
            field=models.BooleanField(default=True, verbose_name='OCCLD'),
        ),
    ]
