# Generated by Django 2.2.16 on 2021-07-06 17:49

from django.db import migrations


def forwards(apps, schema_editor):
    Episode = apps.get_model(
        'opal', 'Episode'
    )
    Episode.objects.filter(
        category_name="OCLD"
    ).update(
        category_name="OCCLD"
    )


def backwards(apps, schema_editor):
    Episode = apps.get_model(
        'opal', 'Episode'
    )
    Episode.objects.filter(
        category_name="OCCLD"
    ).update(
        category_name="OCLD"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0054_auto_20210706_1743'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
