# Generated by Django 2.2.16 on 2021-07-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0055_episode_category_occld'),
        ('rbhl', '0053_cliniclog_cns'),
    ]

    operations = [
    ]
