# Generated by Django 2.2.16 on 2021-11-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0056_merge_20210709_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='attendance',
        ),
    ]
