# Generated by Django 2.2.16 on 2021-11-12 17:33

from django.db import migrations
    # VCD, or Vocal chord dysfunction, ILO --> Upper airway dsfunction

FROM_TO = {
    "Breathing pattern dysfunction": [
        "Breathing pattern disorder",
        "Breathing pattern dysfunction",
        "dysfunctional breathing",
        "BPD",
    ],
    "Upper airway dysfunction": [
        "Induced laryngeal obstruction",
        "ILO", "VCD", "Vocal cord dysfunction",
    ],
    "Irritant symptoms only": [
        "Irritant SX", "Irritant SX only"
    ]
}

def forwards(apps, schema_editor):
    Diagnosis = apps.get_model(
        'rbhl', 'Diagnosis'
    )
    qs = Diagnosis.objects.filter(
        category="Other"
    )
    for new_category, old_conditions in FROM_TO.items():
        for old_condition in old_conditions:
            qs.filter(condition__iexact=old_condition).update(
                category=new_category,
                condition=""
            )

def backwards(apps, schema_editor):
    Diagnosis = apps.get_model(
        'rbhl', 'Diagnosis'
    )
    qs = Diagnosis.objects.all()
    for category in FROM_TO.keys():
        Diagnosis.filter(category=category).update(
            category="Other", condition=category
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0057_remove_referral_attendance'),
    ]

    operations = [
        migrations.RunPython(
            forwards, backwards
        )
    ]
