# Generated by Django 2.2.16 on 2021-11-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0057_remove_referral_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclog',
            name='external_spirometry_done',
            field=models.BooleanField(default=False),
        ),
    ]
