# Generated by Django 2.2.16 on 2021-11-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0058_cliniclog_external_spirometry_done'),
        ('rbhl', '0058_other_diagnosis_to_breathing'),
    ]

    operations = [
    ]
