# Generated by Django 2.2.16 on 2021-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0059_merge_20211120_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='category',
            field=models.CharField(blank=True, choices=[('Asthma', 'Asthma'), ('Rhinitis', 'Rhinitis'), ('Chronic air flow limitation', 'Chronic air flow limitation'), ('Malignancy', 'Malignancy'), ('Benign pleural disease', 'Benign pleural disease'), ('Diffuse lung disease', 'Diffuse lung disease'), ('Breathing pattern dysfunction', 'Breathing pattern dysfunction'), ('Irritant symptoms only', 'Irritant symptoms only'), ('Upper airway dysfunction', 'Upper airway dysfunction'), ('Other', 'Other')], max_length=256, null=True),
        ),
    ]
