# Generated by Django 2.2.16 on 2022-05-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0060_auto_20211126_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliniclog',
            old_name='peak_flow',
            new_name='peak_flow_requested',
        ),
    ]
