# Generated by Django 2.2.16 on 2025-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbhl', '0063_auto_20220527_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referrer_email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Referrer email'),
        ),
    ]
